name: ChristmasEvent2024
version: '${version}'
main: org.hoshizora.christmasevent2024.Main
api-version: '1.20'
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.23
commands:
  dev:
    description: "Get dev command."
    usage: "/dev SoulOverseer"
    permission: eternal.command.dev
  exprefresh:
    description: Refresh your experience points.
    usage: /exprefresh
    permission: ""
  checkexp:
    description: "Check your experience points"
    usage: "/checkexp"
    permission: ""
  devmob:
    description: "Get devmob command."
    usage: "/dev SuiseiNightmare"
    permission: eternal.command.devmob
